name: update-pages

on:
#  schedule:
#    - cron: '0 */24 * * 1'
  workflow_dispatch:

jobs:
  update_notebooks:
    name: Update notebooks with latest data
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Script and Update Notebooks
      run: |
        jupyter nbconvert --execute --to html blotter_demo.ipynb --debug
        jupyter nbconvert --execute --to html earthquakes_demo.ipynb --debug
        jupyter nbconvert --execute --to html fireballs_demo.ipynb --debug

    - name: Commit and Push Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add blotter_demo.html earthquakes_demo.html fireballs_demo.html
        git commit -m "Updated html pages"
        git push origin main
