name: update-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rerun Jupyter Notebook
        run: |
          jupyter nbconvert --execute notebooks/actions_test.ipynb --to notebook --inplace

      - name: Convert Jupyter Notebook to HTML
        run: |
          jupyter nbconvert --output-dir='notebooks/../' --to html notebooks/actions_test.ipynb

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update notebook and html"
          git push
